import Link from "next/link"
import { Plus, Pencil } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { StatusBadge } from "@/components/status-badge"
import { DeleteButton } from "@/components/admin/delete-button"
import { FormShell } from "@/components/admin/form-shell"
import { TextAreaField, TextField, SelectField, StatusField } from "@/components/admin/fields"
import { getSettings, programsRepo, mitraRepo, kegiatanRepo, beritaRepo, dokumentasiRepo, dokumenRepo, publikasiRepo, usersRepo } from "@/lib/store"
import { deleteProgram, deleteMitra, deleteKegiatan, deleteBerita, deleteDokumentasi, deleteDokumen, deletePublikasi, deleteUser, saveProgram, saveMitra, saveKegiatan, saveBerita, saveDokumentasi, saveDokumen, savePublikasi, saveUser, saveSettingsAction } from "../actions"
import { DOKUMEN_JENIS_LABELS, PUBLIKASI_JENIS_LABELS } from "@/lib/types"

type Resource = "profil" | "pengaturan" | "program" | "kegiatan" | "berita" | "dokumentasi" | "dokumen" | "publikasi" | "mitra" | "pengguna"
const labels: Record<Resource, string> = { profil: "Profil", pengaturan: "Pengaturan", program: "Program", kegiatan: "Kegiatan", berita: "Berita", dokumentasi: "Dokumentasi", dokumen: "Dokumen", publikasi: "Publikasi", mitra: "Mitra", pengguna: "Pengguna" }
const repos = { program: programsRepo, mitra: mitraRepo, kegiatan: kegiatanRepo, berita: beritaRepo, dokumentasi: dokumentasiRepo, dokumen: dokumenRepo, publikasi: publikasiRepo, pengguna: usersRepo }
const actions = { program: saveProgram, mitra: saveMitra, kegiatan: saveKegiatan, berita: saveBerita, dokumentasi: saveDokumentasi, dokumen: saveDokumen, publikasi: savePublikasi, pengguna: saveUser }
const deleters = { program: deleteProgram, mitra: deleteMitra, kegiatan: deleteKegiatan, berita: deleteBerita, dokumentasi: deleteDokumentasi, dokumen: deleteDokumen, publikasi: deletePublikasi, pengguna: deleteUser }

function SettingsForm({ settings }: { settings: Awaited<ReturnType<typeof getSettings>> }) {
  return <FormShell action={saveSettingsAction} cancelHref="/admin" submitLabel="Simpan Pengaturan"><div className="grid gap-5 md:grid-cols-2"><TextField name="site_name" label="Nama situs" defaultValue={settings.site_name} required /><TextField name="tagline" label="Tagline" defaultValue={settings.tagline} required /><TextAreaField name="about" label="Profil singkat" defaultValue={settings.about} rows={5} /><TextAreaField name="vision" label="Visi" defaultValue={settings.vision} rows={5} /><TextAreaField name="mission" label="Misi" defaultValue={settings.mission} rows={5} hint="Satu misi per baris." /><TextAreaField name="history" label="Sejarah" defaultValue={settings.history} rows={5} /><TextField name="address" label="Alamat" defaultValue={settings.address} /><TextField name="email" label="Email" type="email" defaultValue={settings.email} /><TextField name="phone" label="Telepon" defaultValue={settings.phone} /><TextField name="facebook" label="Facebook" type="url" defaultValue={settings.facebook} /><TextField name="instagram" label="Instagram" type="url" defaultValue={settings.instagram} /><TextField name="youtube" label="YouTube" type="url" defaultValue={settings.youtube} /></div></FormShell>
}

function EntityForm({ resource, item, kegiatan }: { resource: Exclude<Resource, "profil" | "pengaturan">; item?: Record<string, any>; kegiatan: any[] }) {
  const relationOptions = [{ value: "", label: "Tidak terkait" }, ...kegiatan.map((k) => ({ value: String(k.id), label: k.title }))]
  const id = item?.id ?? null
  let fields: React.ReactNode
  if (resource === "program") fields = <div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Nama program" defaultValue={item?.title} required /><TextField name="icon" label="Ikon" defaultValue={item?.icon} /><TextField name="ordering" label="Urutan" type="number" defaultValue={item?.ordering ?? 0} /><TextAreaField name="description" label="Deskripsi" defaultValue={item?.description} /></div>
  else if (resource === "mitra") fields = <div className="grid gap-5 md:grid-cols-2"><TextField name="nama" label="Nama mitra" defaultValue={item?.nama} required /><TextField name="kategori" label="Kategori" defaultValue={item?.kategori} /><TextField name="website" label="Website" type="url" defaultValue={item?.website} /><TextField name="logo" label="URL logo" type="url" defaultValue={item?.logo} /></div>
  else if (resource === "kegiatan") fields = <><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul kegiatan" defaultValue={item?.title} required /><TextField name="jenis" label="Jenis kegiatan" defaultValue={item?.jenis} required /><TextField name="tanggal" label="Tanggal" type="date" defaultValue={item?.tanggal} required /><TextField name="wilayah" label="Wilayah" defaultValue={item?.wilayah} /><TextField name="lokasi" label="Lokasi" defaultValue={item?.lokasi} /><TextField name="pelaksana" label="Pelaksana" defaultValue={item?.pelaksana} /><TextField name="peserta" label="Peserta" defaultValue={item?.peserta} /><TextField name="foto" label="URL foto" type="url" defaultValue={item?.foto} /><TextField name="video_url" label="URL video" type="url" defaultValue={item?.video_url} /><TextField name="berita_acara" label="URL berita acara" type="url" defaultValue={item?.berita_acara} /><TextField name="laporan" label="URL laporan" type="url" defaultValue={item?.laporan} /><TextField name="proposal" label="URL proposal" type="url" defaultValue={item?.proposal} /></div><div className="grid gap-5 md:grid-cols-2"><TextAreaField name="deskripsi" label="Deskripsi" defaultValue={item?.deskripsi} /><TextAreaField name="tujuan" label="Tujuan" defaultValue={item?.tujuan} /><TextAreaField name="hasil" label="Hasil" defaultValue={item?.hasil} /></div><StatusField defaultValue={item?.status} /></>
  else if (resource === "berita") fields = <><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul berita" defaultValue={item?.title} required /><TextField name="tanggal" label="Tanggal" type="date" defaultValue={item?.tanggal} required /><TextField name="cover" label="URL cover" type="url" defaultValue={item?.cover} /><SelectField name="kegiatan_id" label="Kegiatan terkait" defaultValue={item?.kegiatan_id} options={relationOptions} /></div><TextAreaField name="excerpt" label="Ringkasan" defaultValue={item?.excerpt} /><TextAreaField name="content" label="Isi berita" defaultValue={item?.content} rows={10} /><StatusField defaultValue={item?.status} /></>
  else if (resource === "dokumentasi") fields = <><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul dokumentasi" defaultValue={item?.title} required /><SelectField name="tipe" label="Tipe" defaultValue={item?.tipe} options={[{ value: "foto", label: "Foto" }, { value: "video", label: "Video" }]} /><TextField name="url" label="URL media" type="url" defaultValue={item?.url} required /><TextField name="tanggal" label="Tanggal" type="date" defaultValue={item?.tanggal} /><SelectField name="kegiatan_id" label="Kegiatan terkait" defaultValue={item?.kegiatan_id} options={relationOptions} /></div><StatusField defaultValue={item?.status} /></>
  else if (resource === "dokumen") fields = <><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul dokumen" defaultValue={item?.title} required /><SelectField name="jenis" label="Jenis dokumen" defaultValue={item?.jenis} options={Object.entries(DOKUMEN_JENIS_LABELS).map(([value, label]) => ({ value, label }))} /><TextField name="file_url" label="URL file" type="url" defaultValue={item?.file_url} required /><TextField name="tahun" label="Tahun" type="number" defaultValue={item?.tahun} /><SelectField name="kegiatan_id" label="Kegiatan terkait" defaultValue={item?.kegiatan_id} options={relationOptions} /></div><StatusField defaultValue={item?.status} /></>
  else if (resource === "publikasi") fields = <><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul publikasi" defaultValue={item?.title} required /><SelectField name="jenis" label="Jenis publikasi" defaultValue={item?.jenis} options={Object.entries(PUBLIKASI_JENIS_LABELS).map(([value, label]) => ({ value, label }))} /><TextField name="authors" label="Penulis" defaultValue={item?.authors} /><TextField name="tahun" label="Tahun" type="number" defaultValue={item?.tahun} /><TextField name="link" label="URL publikasi" type="url" defaultValue={item?.link} /><SelectField name="kegiatan_id" label="Kegiatan terkait" defaultValue={item?.kegiatan_id} options={relationOptions} /></div><TextAreaField name="abstract" label="Abstrak" defaultValue={item?.abstract} rows={8} /><StatusField defaultValue={item?.status} /></>
  else fields = <div className="grid gap-5 md:grid-cols-2"><TextField name="name" label="Nama" defaultValue={item?.name} required /><TextField name="email" label="Email" type="email" defaultValue={item?.email} required /><TextField name="password" label="Kata sandi" type="password" required={!id} hint={id ? "Kosongkan jika tidak ingin mengubah." : undefined} /><SelectField name="role" label="Peran" defaultValue={item?.role ?? "editor"} options={[{ value: "admin", label: "Admin" }, { value: "editor", label: "Editor" }]} /></div>
  return <FormShell action={(id ? actions[resource].bind(null, id) : actions[resource].bind(null, null)) as any} cancelHref={`/admin/${resource}`} submitLabel={id ? "Simpan Perubahan" : "Tambah Data"}>{fields}</FormShell>
}

export default async function AdminResourcePage({ params }: { params: Promise<{ resource: string }> }) {
  const { resource: raw } = await params
  const resource = raw as Resource
  if (!(resource in labels)) return <p>Halaman admin tidak ditemukan.</p>
  if (resource === "profil" || resource === "pengaturan") {
    const settings = await getSettings()
    return <div className="space-y-6"><div><h1 className="text-2xl font-bold">{labels[resource]}</h1><p className="mt-1 text-sm text-muted-foreground">Kelola informasi yang tampil di website publik.</p></div><SettingsForm settings={settings} /></div>
  }
  const repoKey = resource as keyof typeof repos
  const [items, kegiatan] = await Promise.all([repos[repoKey].all(), kegiatanRepo.all()])
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{labels[resource]}</h1><p className="mt-1 text-sm text-muted-foreground">Kelola, verifikasi, dan publikasikan data {labels[resource].toLowerCase()}.</p></div><Button asChild><Link href={`/admin/${resource}/baru`}><Plus className="mr-1 h-4 w-4" />Tambah</Link></Button></div><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-secondary/40 text-left"><tr><th className="px-4 py-3 font-medium">Nama / Judul</th><th className="px-4 py-3 font-medium">Info</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 text-right font-medium">Aksi</th></tr></thead><tbody>{(items as any[]).map((item) => <tr key={item.id} className="border-b last:border-0"><td className="max-w-sm px-4 py-3"><p className="truncate font-medium">{resource === "mitra" ? item.nama : resource === "pengguna" ? item.name : item.title}</p><p className="text-xs text-muted-foreground">#{item.id}</p></td><td className="px-4 py-3 text-muted-foreground">{item.tahun ?? item.kategori ?? item.email ?? item.jenis ?? "-"}</td><td className="px-4 py-3">{item.status ? <StatusBadge status={item.status} /> : <span className="text-muted-foreground">Aktif</span>}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button asChild size="icon" variant="ghost" title="Edit"><Link href={`/admin/${resource}/${item.id}`}><Pencil className="h-4 w-4" /></Link></Button><DeleteButton action={deleters[resource].bind(null, item.id)} /></div></td></tr>)}</tbody></table></div>{items.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">Belum ada data.</p>}</CardContent></Card></div>
}