import { FormShell } from "@/components/admin/form-shell"
import { TextAreaField, TextField, SelectField, StatusField, FileField } from "@/components/admin/fields"
import { DOKUMEN_JENIS_LABELS, PUBLIKASI_JENIS_LABELS } from "@/lib/types"
import { programsRepo, mitraRepo, kegiatanRepo, beritaRepo, dokumentasiRepo, dokumenRepo, publikasiRepo, usersRepo } from "@/lib/store"
import { saveProgram, saveMitra, saveKegiatan, saveBerita, saveDokumentasi, saveDokumen, savePublikasi, saveUser } from "@/app/admin/(dashboard)/actions"

type Resource = keyof typeof actions
const actions = { program: saveProgram, mitra: saveMitra, kegiatan: saveKegiatan, berita: saveBerita, dokumentasi: saveDokumentasi, dokumen: saveDokumen, publikasi: savePublikasi, pengguna: saveUser }

export function EntityForm({ resource, item, kegiatan }: { resource: Resource; item?: Record<string, any>; kegiatan: any[] }) {
  const relationOptions = [{ value: "", label: "Tidak terkait" }, ...kegiatan.map((k) => ({ value: String(k.id), label: k.title }))]
  const id = item?.id ?? null
  let fields: React.ReactNode
  if (resource === "program") fields = <div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Nama program" defaultValue={item?.title} required /><TextField name="icon" label="Ikon" defaultValue={item?.icon} /><TextField name="ordering" label="Urutan" type="number" defaultValue={item?.ordering ?? 0} /><TextAreaField name="description" label="Deskripsi" defaultValue={item?.description} /></div>
  else if (resource === "mitra") fields = <div className="grid gap-5 md:grid-cols-2"><TextField name="nama" label="Nama mitra" defaultValue={item?.nama} required /><TextField name="kategori" label="Kategori" defaultValue={item?.kategori} /><TextField name="website" label="Website" type="url" defaultValue={item?.website} /><TextField name="logo" label="URL logo" type="url" defaultValue={item?.logo} /></div>
  else if (resource === "kegiatan") fields = <><input type="hidden" name="foto_existing" value={item?.foto ?? ""} /><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul kegiatan" defaultValue={item?.title} required /><TextField name="jenis" label="Jenis kegiatan" defaultValue={item?.jenis} required /><TextField name="tanggal" label="Tanggal" type="date" defaultValue={item?.tanggal} required /><TextField name="wilayah" label="Wilayah" defaultValue={item?.wilayah} /><TextField name="lokasi" label="Lokasi" defaultValue={item?.lokasi} /><TextField name="pelaksana" label="Pelaksana" defaultValue={item?.pelaksana} /><TextField name="peserta" label="Peserta" defaultValue={item?.peserta} /><FileField name="foto" label="Foto kegiatan" accept="image/*" hint={item?.foto ? "Kosongkan untuk mempertahankan foto saat ini." : "Maksimal 10 MB."} /><TextField name="video_url" label="URL video" type="url" defaultValue={item?.video_url} /><TextField name="berita_acara" label="URL berita acara" type="url" defaultValue={item?.berita_acara} /><TextField name="laporan" label="URL laporan" type="url" defaultValue={item?.laporan} /><TextField name="proposal" label="URL proposal" type="url" defaultValue={item?.proposal} /></div><div className="grid gap-5 md:grid-cols-2"><TextAreaField name="deskripsi" label="Deskripsi" defaultValue={item?.deskripsi} /><TextAreaField name="tujuan" label="Tujuan" defaultValue={item?.tujuan} /><TextAreaField name="hasil" label="Hasil" defaultValue={item?.hasil} /></div><StatusField defaultValue={item?.status} /></>
  else if (resource === "berita") fields = <><input type="hidden" name="cover_existing" value={item?.cover ?? ""} /><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul berita" defaultValue={item?.title} required /><TextField name="tanggal" label="Tanggal" type="date" defaultValue={item?.tanggal} required /><FileField name="cover" label="Cover berita" accept="image/*" /><SelectField name="kegiatan_id" label="Kegiatan terkait" defaultValue={item?.kegiatan_id} options={relationOptions} /></div><TextAreaField name="excerpt" label="Ringkasan" defaultValue={item?.excerpt} /><TextAreaField name="content" label="Isi berita" defaultValue={item?.content} rows={10} /><StatusField defaultValue={item?.status} /></>
  else if (resource === "dokumentasi") fields = <><input type="hidden" name="url_existing" value={item?.url ?? ""} /><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul dokumentasi" defaultValue={item?.title} required /><SelectField name="tipe" label="Tipe" defaultValue={item?.tipe} options={[{ value: "foto", label: "Foto" }, { value: "video", label: "Video" }]} /><FileField name="url" label="File foto/video" accept="image/*,video/*" /><TextField name="tanggal" label="Tanggal" type="date" defaultValue={item?.tanggal} /><SelectField name="kegiatan_id" label="Kegiatan terkait" defaultValue={item?.kegiatan_id} options={relationOptions} /></div><StatusField defaultValue={item?.status} /></>
  else if (resource === "dokumen") fields = <><input type="hidden" name="file_url_existing" value={item?.file_url ?? ""} /><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul dokumen" defaultValue={item?.title} required /><SelectField name="jenis" label="Jenis dokumen" defaultValue={item?.jenis} options={Object.entries(DOKUMEN_JENIS_LABELS).map(([value, label]) => ({ value, label }))} /><FileField name="file_url" label="File dokumen" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx" hint="Maksimal 10 MB." /><TextField name="tahun" label="Tahun" type="number" defaultValue={item?.tahun} /><SelectField name="kegiatan_id" label="Kegiatan terkait" defaultValue={item?.kegiatan_id} options={relationOptions} /></div><StatusField defaultValue={item?.status} /></>
  else if (resource === "publikasi") fields = <><div className="grid gap-5 md:grid-cols-2"><TextField name="title" label="Judul publikasi" defaultValue={item?.title} required /><SelectField name="jenis" label="Jenis publikasi" defaultValue={item?.jenis} options={Object.entries(PUBLIKASI_JENIS_LABELS).map(([value, label]) => ({ value, label }))} /><TextField name="authors" label="Penulis" defaultValue={item?.authors} /><TextField name="tahun" label="Tahun" type="number" defaultValue={item?.tahun} /><TextField name="link" label="URL publikasi" type="url" defaultValue={item?.link} /><SelectField name="kegiatan_id" label="Kegiatan terkait" defaultValue={item?.kegiatan_id} options={relationOptions} /></div><TextAreaField name="abstract" label="Abstrak" defaultValue={item?.abstract} rows={8} /><StatusField defaultValue={item?.status} /></>
  else fields = <div className="grid gap-5 md:grid-cols-2"><TextField name="name" label="Nama" defaultValue={item?.name} required /><TextField name="email" label="Email" type="email" defaultValue={item?.email} required /><TextField name="password" label="Kata sandi" type="password" required={!id} hint={id ? "Kosongkan jika tidak ingin mengubah." : undefined} /><SelectField name="role" label="Peran" defaultValue={item?.role ?? "editor"} options={[{ value: "admin", label: "Admin" }, { value: "editor", label: "Editor" }]} /></div>
  return <FormShell action={(id ? actions[resource].bind(null, id) : actions[resource].bind(null, null)) as any} cancelHref={`/admin/${resource}`} submitLabel={id ? "Simpan Perubahan" : "Tambah Data"}>{fields}</FormShell>
}
